# Generated by Django 3.2.8 on 2022-05-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterlog', '0003_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='amount',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='source',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='target',
            field=models.TextField(),
        ),
    ]
