# Generated by Django 3.2.8 on 2022-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterlog', '0004_auto_20220504_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='owner',
            field=models.TextField(),
        ),
    ]
