# Generated by Django 3.2.8 on 2022-05-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afterlog', '0005_alter_coupon_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
    ]
